#! /bin/bash
NAME=$(grep "^NAME=" .env | sed "s/NAME=//")
# Тесты запускаются В Docker контейнере backend
# Для прогона тесток сервисы должны быть запущены
docker exec --tty $NAME-backend npm test $@
