#! /bin/bash
NAME=$(grep "^NAME=" .env | sed "s/NAME=//")
STORAGE_USER=$(grep "^STORAGE_USER=" .env | sed "s/STORAGE_USER=//")
STORAGE_SECRET=$(grep "^STORAGE_SECRET=" .env | sed "s/STORAGE_SECRET=//")
NET=${NAME}_default

# Не передает параметры - настроить!
#docker run -it --net=$NET --entrypoint=/bin/bash minio/mc 
#docker run -it --net=$NET minio/mc alias set storage http://storage:9000 Q3AM3UQ867SPQQA43P2F zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
docker run --tty --net=$NET minio/mc $@

